services:
    bot:
        build: 
            context: ./apps/bot
            dockerfile: Dockerfile
        container_name: jasper-bot
        environment:
            - BOTID=${BOTID}
            - PUBLICKEY=${PUBLICKEY}
            - TOKEN=${TOKEN}
            - MONGODB=mongodb://mongo:27017/jasper
            - PREFIX=${PREFIX}
            - GUILD_ONLY_COMMANDS=${GUILD_ONLY_COMMANDS}
            - GUILD_ONLY_COMMANDS_GUILD_ID=${GUILD_ONLY_COMMANDS_GUILD_ID}
            - YOUTUBE_CHANNEL_ID=${YOUTUBE_CHANNEL_ID}
            - YOUTUBE_KEY=${YOUTUBE_KEY}
            - YOUTUBE_KEY_TWO=${YOUTUBE_KEY_TWO}
            - YOUTUBE_KEY_THREE=${YOUTUBE_KEY_THREE}
            - YOUTUBE_VIDEO_POST_CHANNEL_ID=${YOUTUBE_VIDEO_POST_CHANNEL_ID}
            - YOUTUBE_VIDEO_POST_TIMER=${YOUTUBE_VIDEO_POST_TIMER}
            - YOUTUBE_VIDEO_POST_UPDATE=${YOUTUBE_VIDEO_POST_UPDATE}
            - YOUTUBE_VIDEO_DISCUSSIONS_ROLE_ID=${YOUTUBE_VIDEO_DISCUSSIONS_ROLE_ID}
            - SUB_COUNT_CHANNEL=${SUB_COUNT_CHANNEL}
            - SUB_COUNT_TIMER=${SUB_COUNT_TIMER}
            - SUB_COUNT_UPDATE=${SUB_COUNT_UPDATE}
            - REDISHOST=redis
            - REDISPORT=6379
            - SLOWMODE=${SLOWMODE}
            - SLOWMODE_COOLDOWN=${SLOWMODE_COOLDOWN}
            - SLOWMODE_MESSAGE_TIME=${SLOWMODE_MESSAGE_TIME}
            - SLOWMODE_MESSAGE_THRESHOLD=${SLOWMODE_MESSAGE_THRESHOLD}
            - SLOWMODE_RESET_SLOWMODE=${SLOWMODE_RESET_SLOWMODE}
            - SLOWMODE_RESET_TIME=${SLOWMODE_RESET_TIME}
        depends_on:
            - mongo
            - redis

    webserver:
        build:
            context: ./apps/webserver
            dockerfile: Dockerfile
        container_name: jasper-webserver
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/jasper
            - SPRING_REDIS_HOST=redis
            - SPRING_REDIS_PORT=6379
        depends_on:
            - mongo
            - redis

    worker:
        build:
            context: ./apps/worker
            dockerfile: Dockerfile
        container_name: jasper-worker
        environment:
            - BOTID=${BOTID}
            - PUBLICKEY=${PUBLICKEY}
            - TOKEN=${TOKEN}
        ports:
            - "8787:8787"

    mongo:
        image: mongo:latest
        container_name: jasper-mongo
        volumes:
            - mongo-data:/data/db

    redis:
        image: redis:latest
        container_name: jasper-redis

volumes:
    mongo-data:
