services:
  jasper_redis:
    image: redis:latest
    container_name: jasper_redis
    restart: unless-stopped
    env_file:
      - ./env/redis.env
    volumes:
      - ./volumes/redis_data:/data
    ports:
      - "6379:6379"

  jasper_mongo:
    image: mongo:8-noble
    container_name: jasper_mongo
    restart: unless-stopped
    env_file:
      - ./env/mongo.env
    volumes:
      - ./volumes/mongodb_data:/data/db
    ports:
      - "27017:27017"
